class Event:
    CLIENT_DISCONNECTION_PUBLISHED = "client_disconnection_published"
    POSITION_UPDATED = "position_updated"
    MODEL_UPDATED = "model_updated"
    ANIMATION_UPDATED = "animation_updated"
    HEALTH_UPDATED = "health_updated"
    MANA_UPDATED = "mana_updated"
    NAME_UPDATED = "name_updated"
    NEW_PLAYER_JOINED = "new_player_joined"
    WEAPON_UPDATED = "weapon_updated"
    DISCONNECTION = "disconnection"
    COMBAT_DATA_CREATED = "combat_data_created"
    TEXT_MESSAGE = "text_message"
