class Message:
    ASK_FOR_PASS = 0
    ASK_FOR_INITIAL_DATA = 1
    REQUEST_MODEL = 2
    WELCOME_MSG = 3
    POS_HPR = 50
    ANIMATION = 51
    ACTION = 52
    DISCONNECTION = 53
    CHAT_MSG = 54
    CHARACTER_REACTION = 100
    TELEPORT = 101
    NEW_PLAYER = 102
    HEALTH = 103
    READY_FOR_UPDATES = 150